name: Build AppWithVelopackInstaller

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: pwsh
    
env:
  version: "1.0.${{ github.run_number }}"
  
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build
        run: dotnet build --configuration Release -p:Version="${{ env.version }}"

      - name: Publish
        if: ${{ github.event_name != 'pull_request' }}
        run: ./publish.ps1 -Version ${{ env.version }}

      - name: Prepare release
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/create-release@v1.1.4
        id: create_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          draft: false
          prerelease: false
          release_name: ${{ env.version }}
          tag_name: ${{ env.version }}

      - name: Upload release artifact
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./publish/*
          asset_name: artifacts.zip
          asset_content_type: application/zip