name: Build AppWithVelopackInstaller

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: pwsh
    
env:
  version: "1.0.${{ github.run_number }}"
  
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build
        run: dotnet build --configuration Release -p:Version="${{ env.version }}"

      - name: Publish
        if: ${{ github.event_name != 'pull_request' }}
        run: ./publish.ps1 -Version ${{ env.version }}

      - name: Create release
        if: ${{ github.event_name != 'pull_request' }}
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "publish/*"
          body: "Release ${{ env.version }}"
          tag: "v${{ env.version }}"
          commit: ${{ github.sha }}